//Count and say
/* The count-and-say sequence is a sequence of digit strings defined by the following recursive formula:
   countAndSay(1) = "1"
   For n > 1, countAndSay(n) is generated by describing countAndSay(n-1) in terms of the frequency and value of consecutive identical digits.
   
*/
class Solution {
public:
    string countAndSay(int n) {
        string ans = "1";

        for(int i=2; i<=n; i++){
            string temp = "";

            for(int j=0; j<ans.size();){
                int count = 1;

                while(j+count < ans.size() && ans[j] == ans[j+count]){
                    count++;
                }

                temp += to_string(count);
                temp += ans[j];

                j += count;
            }
            ans = temp;
        }
        return ans;
    }
};