//Count and say
/* The count-and-say sequence is a sequence of digit strings defined by the following recursive formula:
   countAndSay(1) = "1"
   For n > 1, countAndSay(n) is generated by describing countAndSay(n-1) in terms of the frequency and value of consecutive identical digits.
   
*/